"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createCourse, getCourseById, updateCourse } from "@/features";
import { validateCourse } from "@/features/courses/course.validation";
export default function CourseFormPage({courseId}) {
 const router=useRouter(); const [form,setForm]=useState({title:"",description:"",accessType:"free",price:"",validityDays:"",status:"published"}); const [loading,setLoading]=useState(Boolean(courseId)); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
 useEffect(()=>{if(!courseId)return;getCourseById(courseId).then(course=>{if(course)setForm({title:course.title||"",description:course.description||"",accessType:course.accessType||"free",price:course.price?String(course.price):"",validityDays:course.validityDays?String(course.validityDays):"",status:course.status||"published"});setLoading(false);});},[courseId]);
 const submit=async(e)=>{e.preventDefault();setSaving(true);setError("");try{const payload=validateCourse({...form,price:form.accessType==="paid"?Number(form.price):0,validityDays:form.accessType==="paid"?Number(form.validityDays):null});const id=courseId||await createCourse(payload);if(courseId)await updateCourse(courseId,payload);router.push(`/admin/dashboard/courses/${id}/lessons`);}catch(err){setError(err.message||"Unable to save course.");}finally{setSaving(false);}};
 if(loading)return <main style={styles.page}>Loading course...</main>;
 return <main style={styles.page}><form onSubmit={submit} style={styles.card}><h1>{courseId?"Edit Course":"Create Course"}</h1><label style={styles.label}>Course title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} style={styles.input}/></label><label style={styles.label}>Description<textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})} style={styles.textarea}/></label><label style={styles.label}>Access<select value={form.accessType} onChange={e=>setForm({...form,accessType:e.target.value})} style={styles.input}><option value="free">Free</option><option value="paid">Paid</option></select></label>{form.accessType==="paid"&&<><label style={styles.label}>Price (INR)<input type="number" min="1" step="0.01" required value={form.price} onChange={e=>setForm({...form,price:e.target.value})} style={styles.input}/></label><label style={styles.label}>Access validity (days)<input type="number" min="1" step="1" placeholder="Example: 60 or 90" required value={form.validityDays} onChange={e=>setForm({...form,validityDays:e.target.value})} style={styles.input}/></label></>}<label style={styles.label}>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} style={styles.input}><option value="published">Published</option><option value="draft">Draft</option></select></label>{error&&<p style={styles.error}>{error}</p>}<button disabled={saving} style={styles.button}>{saving?"Saving...":"Save and manage lessons"}</button></form></main>;
}
const styles={page:{minHeight:"100vh",background:"#f7f0ea",padding:"40px 20px"},card:{maxWidth:700,margin:"0 auto",background:"#fff",borderRadius:18,padding:28,display:"grid",gap:18},label:{display:"grid",gap:8,fontWeight:700},input:{padding:"12px 14px",borderRadius:10,border:"1px solid #e8dbbf",fontSize:16},textarea:{minHeight:120,padding:"12px 14px",borderRadius:10,border:"1px solid #e8dbbf",fontSize:16},button:{background:"#172120",color:"#fff",border:0,borderRadius:10,padding:"14px 18px",fontWeight:700},error:{color:"#b42318",fontWeight:600}};
