"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { onAuthStateChanged } from "firebase/auth";
import { browserAuth } from "@/lib/firebase/client-auth";
import { getCourseById, getEnrollmentsByUser } from "@/features";
import CourseThumbnail from "@/features/courses/components/CourseThumbnail";
export default function MyCoursesPage(){const [courses,setCourses]=useState([]);useEffect(()=>onAuthStateChanged(browserAuth,async user=>{if(!user)return;const enrollments=await getEnrollmentsByUser(user.uid);const items=await Promise.all(enrollments.filter(e=>e.status==="enrolled").map(async e=>({enrollment:e,course:await getCourseById(e.courseId)})));setCourses(items.filter(i=>i.course?.status==="published"));}),[]);return <main style={styles.page}><div style={styles.container}><p style={styles.eyebrow}>Your learning</p><h1 style={styles.title}>My Courses</h1><section style={styles.grid}>{courses.map(({course,enrollment})=><article key={course.id} style={styles.card}><CourseThumbnail course={course} compact/><span style={styles.badge}>{enrollment.accessType==="paid"?"Purchased":"Free enrollment"}</span><h2>{course.title}</h2><p>{course.description}</p><Link href={`/dashboard/courses/${course.id}`} style={styles.button}>Continue learning</Link></article>)}{!courses.length&&<p>You have not enrolled in a course yet. <Link href="/dashboard/courses">Browse courses</Link></p>}</section></div></main>}
const styles={page:{minHeight:"100vh",padding:"32px 20px",background:"#f7f1e9"},container:{maxWidth:1100,margin:"0 auto"},eyebrow:{margin:0,color:"#ff724f",fontWeight:800,textTransform:"uppercase"},title:{fontSize:38,margin:"7px 0 24px"},grid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(250px,1fr))",gap:16},card:{background:"#fff",borderRadius:14,padding:18},badge:{fontWeight:800,color:"#157347"},button:{display:"inline-block",background:"#172120",color:"#fff",borderRadius:9,padding:"11px 14px",fontWeight:700}};
